### ISSUE TITLE
Dump database to fixtures

### ISSUE THREAD

**Issue by Bobliuuu** [Hackathons-Canada/HackathonsCanada#5]

**Comment by Bobliuuu** [comment]
Requires #4 as a prerequisite

**Comment by JasonLovesDoggo** [comment]
wym by dump db? which db?

**Comment by Bobliuuu** [comment]
Dump the SQLite DB into Django (https://docs.djangoproject.com/en/5.0/ref/django-admin/#dumpdata)
But since we don't wanna do this a lot the duplicates should be removed first.

**Comment by JasonLovesDoggo** [comment]
> Dump the SQLite DB into Django (https://docs.djangoproject.com/en/5.0/ref/django-admin/#dumpdata) But since we don't wanna do this a lot the duplicates should be removed first.

Ah I see your mistake, dumpdata doesn't import TO Django it exports the current DB into a cross-compatible format called a fixture (which you can specify to be json,xml,yml,ect...)

loaddata takes those fixtures and imports them into the DB

**Comment by JasonLovesDoggo** [comment]
closed as this is now not strictly needed as we are using neondb for prod/dev branches
